# Generated by Django 4.2.3 on 2023-07-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('profile', models.CharField(choices=[('software_engineer', 'Software Engineer'), ('product_manager', 'Product Manager'), ('data_scientist', 'Data Scientist')], max_length=50)),
                ('job_type', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('internship', 'Internship'), ('full_time', 'Full-time')], max_length=50)),
            ],
        ),
    ]
