# Generated by Django 4.2.3 on 2023-07-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_company_joblisting_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract')], max_length=20)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='JobListing',
        ),
    ]
